//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cure.WebAdmin.Admin {
    
    
    public partial class SoonList {
        
        /// <summary>
        /// uxSoonVisitsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cure.WebAdmin.Admin.Controls.SoonVisitsList uxSoonVisitsList;
        
        /// <summary>
        /// uxCurrentVisitsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UserControl uxCurrentVisitsList;
        
        /// <summary>
        /// uxJustClosedVisitsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cure.WebAdmin.Admin.Controls.JustClosedVisitsList uxJustClosedVisitsList;
    }
}
